live_config_reload = false

[colors.bright]
black = "0x575b70"
blue = "0xcaa9fa"
cyan = "0x9aedfe"
green = "0x5af78e"
magenta = "0xff92d0"
red = "0xff6e67"
white = "0xe6e6e6"
yellow = "0xf4f99d"

[colors.normal]
black = "0x333333"
blue = "0xcaa9fa"
cyan = "0x8be9fd"
green = "0x50fa7b"
magenta = "0xff79c6"
red = "0xff5555"
white = "0xbfbfbf"
yellow = "0xf1fa8c"

[colors.primary]
background = "0x000000"
foreground = "0xf8f8f2"

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
family = "Hack"

[font.normal]
family = "Hack"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[window]
decorations = "none"
startup_mode = "Fullscreen"

[window.padding]
x = 16
y = 16
